### ISSUE TITLE
"place" -> "songs"

### ISSUE THREAD

**Issue by rattrayalex** [jahlela/triptunes#12]
basically, get all possible songs from the name of the place - can filter them later

**Comment by jahlela** [comment]
We're going to make simple GET requests to e.g. http://www.lyrics.com/lyrics/san%20francisco and use https://cheerio.js.org/ to scrape the HTML for the search results. 

Title: 
    `#content-body > div > div:nth-child(6) > div > p.lyric-meta-title > a`
    `<a href="/lyric/10360832">San Francisco Lights</a>`

Original Artist:
    `#content-body > div > div:nth-child(6) > div > p.lyric-meta-artists > a`
    `<a href="artist/Bobbi%20Humphrey/6781">Bobbi Humphrey</a>`

Album: 
    `#content-body > div > div:nth-child(7) > div > p.lyric-meta-album > a`
    `<a href="/album/463401">Diggin' on Blue</a>`

Album Artist: 
    `#content-body > div > div:nth-child(6) > div > p.lyric-meta-album-artist > a`
    `<a href="artist/Lord%20Finesse/76079">Lord Finesse</a>`

**Comment by jahlela** [comment]
Alternatively, we can grab all instances of `.sec-lyric clearfix`, and iterate over each, extracting:
* .lyric-meta-title
* .lyric-meta-artists
* .lyric-meta-album
* .lyric-meta-album-artist

**Comment by jahlela** [comment]
Spotify example call `https://api.spotify.com/v1/search?q=track:san%20francisco%20lights%20artist:bobbi%20humphrey&type=track`

**Comment by rattrayalex** [comment]
I think we're doing this?
